name: 'kubernetes-rollback-action'
description: 'An action to handle kubectl interaction for kube rollbacks'
author: 'Smartly.io'
inputs:
  # Expects to be pre-configured with smartlyio/kubernetes-auth-token@v1
  kubernetesContext:
    description: 'Kubernetes context name. Usually the name of the cluster, but can be random.'
    required: true
  serviceName:
    description: 'Name of the service'
    required: true
  deploymentName:
    description: 'Name of the deployment within service to operate rollbacks on'
    required: true
  command:
    description: 'Rollback support command to run. One of [listRecentDeploys|checkRevision]'
    required: true
  rollbackSha:
    description: 'Git revision to validate with the `checkRevision` command.'
    required: false
outputs:
  SLACK_NOTIFICATION_MESSAGE:
    description: 'A message that should be sent to slack as a response to the command.'
  ALLOW_ROLLBACK:
    description: 'Whether or not rollback should be allowed. true/false.'
runs:
  using: 'node16'
  main: 'dist/index.js'
