name: Build

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Set Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: "Install"
      run: |
        npm install
    - name: "Prettier"
      run: |
        npm run format-check
    - name: "Lint"
      run: |
        npm run lint
    - name: "Test"
      run: |
        npm run test
    - name: "build"
      run: |
        npm run build
        npm run package

  test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Set Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: "Build action for test"
      run: |
        npm install
        npm run all
        git clean -fXd
    - name: Mock the kubectl binary
      run: |
        echo "$(pwd)/__tests__/bin" >> "$GITHUB_PATH"
    - name: List recent deployments
      uses: ./
      with: 
        serviceName: test-service
        kubernetesContext: test-context
        command: listRecentDeploys
        deploymentName: deployment
    - name: Validate a redeploy revision
      uses: ./
      with:
        serviceName: test-service
        kubernetesContext: test-context
        command: checkRevision
        rollbackSha: abc123
        deploymentName: deployment

  release:
    runs-on: ubuntu-24.04
    name: "Build and release action"
    needs: [build, test]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Configure git
        uses: smartlyio/github-actions@git-init-userinfo-v1
      - name: Release flow
        uses: smartlyio/github-actions@release-action-node-v1
        with:
          dry_run: ${{ github.event_name == 'pull_request' }}
          token: "${{ secrets.GITHUB_TOKEN }}"
